canonical/craft-store

- craft_store/attenuations.py
> attenuations: new module with documented constants (CRAFT-453)

- .pylintrc
- craft_store/errors.py
- craft_store/store_client.py
- setup.cfg
- tests/unit/test_errors.py
- tests/unit/test_store_client.py
- tox.ini
> store client: use in-house WebBrowserInteractor for candid (CRAFT-563)

- craft_store/__init__.py
> release: 0.0.1.dev2

- docs/index.rst
- docs/tutorials.rst
> docs: add login and whoami tutorials for Snap Store

- README.md
Add some simple instructions to make it easier for collaborators to
have an as frictionless experience as possible.
-------
-----
> readme: document how to contribute and work with the project

- docs/index.rst
- docs/tutorials.rst
> docs: update toc and incorrect labels

- craft_store/auth.py
- tests/unit/test_auth.py
This clarifies the logs, the keyring is now also retrieved on Auth
initialization to avoid having it change by any external circumstance.
-------
-----
> auth: log the keyring name (CRAFT-658)

- craft_store/store_client.py
- docs/howtos.rst
- docs/index.rst
> docs: add how-to for using credentials from the environment (CRAFT-649)

- craft_store/__init__.py
- docs/changelog.rst
> release: 1.1.0 (CRAFT-645)

- docs/tutorials.rst
- [:heavy_check_mark: ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
Docs change to fix typo in name of the script.
> docs: fix typo in name of whoami script

- craft_store/__init__.py
- craft_store/endpoints.py
- craft_store/ubuntu_one_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
This implementation is meant to work with Ubuntu One as the
authentication provider.
-------
-----
> ubuntu one store client: new component (CRAFT-691)

- docs/tutorials.rst
> docs: tutorial for logging in using Ubuntu One (CRAFT-692)

- craft_store/__init__.py
- docs/changelog.rst
> release 1.2.0 (CRAFT-703)

- docs/tutorials.rst
> docs: add a tutorial for uploading snaps with simple progress (CRAFT-735)

- craft_store/base_client.py
- docs/howtos.rst
- docs/tutorials.rst
- tests/unit/test_store_client.py
> docs: add howto on uploading with progress from craft-cli (CRAFT-736)

- craft_store/auth.py
- craft_store/base_client.py
- craft_store/errors.py
- tests/integration/test_auth.py
- tests/unit/test_auth.py
- tests/unit/test_errors.py
- tests/unit/test_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
> auth: do not allow overwriting existing credentials (CRAFT-776)

- craft_store/auth.py
- craft_store/base_client.py
- tests/unit/test_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
Gives a better sense of its purpose.
-----
> auth: rename validate_set_credentials to ensure_no_credentials

- craft_store/auth.py
- craft_store/errors.py
- tests/unit/test_auth.py
- tests/unit/test_errors.py
> errors: rename CredentialsAvailable to CredentialsAlreadyAvailable

- craft_store/__init__.py
- docs/changelog.rst
> release: 2.0.0 (CRAFT-772)

- craft_store/base_client.py
> base client: improve doc strings (CRAFT-799)

- docs/changelog.rst
> release: 2.0.1

- .github/workflows/tests.yaml
- setup.cfg
> ci: enable Python 3.10 (CRAFT-744)

- .github/workflows/tests.yaml
- craft_store/__init__.py
- craft_store/base_client.py
- craft_store/endpoints.py
- craft_store/models/__init__.py
- craft_store/models/_base_model.py
- craft_store/models/_common_list_releases_model.py
- craft_store/models/charm_list_releases_model.py
- craft_store/models/snap_list_releases_model.py
- craft_store/ubuntu_one_store_client.py
- tests/integration/test_get_list_releases.py
- tests/unit/models/test_charm_list_releases_model.py
- tests/unit/models/test_snap_list_releases_model.py
Introduce the namespaced endpoint with pydantic validation.
-----
CRAFT-951
> base client: support list-releases

- craft_store/base_client.py
- craft_store/models/__init__.py
- craft_store/models/release_request_model.py
- tests/integration/test_release.py
- tests/unit/models/test_request_release_model.py
> base client: support releasing

- craft_store/auth.py
- craft_store/base_client.py
- pyproject.toml
- tests/unit/test_auth.py
- tests/unit/test_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
> auth: allow for ephemeral logins

- craft_store/store_client.py
- craft_store/ubuntu_one_store_client.py
- tests/unit/test_auth.py
- tests/unit/test_store_client.py
> store client: add ephemeral login

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
> release 2.1.0

- craft_store/endpoints.py
It is common across all environments so far.
-----
CRAFT-1236
> endpoints: move upload endpoint to Endpoints

- craft_store/models/__init__.py
> models: export classes for easier consumption

- craft_store/errors.py
- tests/unit/test_errors.py
- tests/unit/test_http_client.py
> errors: catch the correct JSONDecodeError

- craft_store/endpoints.py
- tests/unit/test_endpoints.py
> endpoints: urlpath generator for releases and revisions

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
> release: 2.2.0

- craft_store/models/__init__.py
- craft_store/models/snap_list_releases_model.py
Also make base optional (as defined by the API).
-----
> models: export correct release models

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
> release 2.2.1

- .github/workflows/tests.yaml
- tests/integration/test_get_list_releases.py
- tests/integration/test_release.py
- tests/integration/test_upload.py
> ci: macos 10 -> 12 for GHA

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
- [x Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
> Release 2.3.0

- README.md
> docs: document getting credentials for integration tests

- craft_store/auth.py
- craft_store/base_client.py
- craft_store/creds.py
- craft_store/store_client.py
- craft_store/ubuntu_one_store_client.py
- docs/conf.py
- pyproject.toml
- setup.cfg
- setup.py
- tests/unit/test_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
> lint: fix linting issues with up-to-date linters

- craft_store/models/release_request_model.py
- tests/integration/conftest.py
- tests/integration/test_get_list_releases.py
Also includes a brief instruction for replicating the test.
-----
> tests: update store tests for new image

- craft_store/base_client.py
The upload_file method should log the total size before starting to work
- [Yes] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----
> Issue: #68

- setup.cfg
> deps: freeze pydantic <2.0

- pyrightconfig.json
> test(lint): make pyright ignore _version.py

- README.md
Add the badge as well
-----
Fixes #101
> docs: new link to docs

- setup.cfg
- [ Yes ] Have you followed the guidelines for contributing?
- [ Yes ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ Yes ] Have you successfully run `tox`?
-----
> #64 set 2.27 version number as minimum for requests package in setup.cfg

- pyproject.toml
- tox.ini
> style: remove pylint

- .bumpversion.cfg
- craft_store/__init__.py
- docs/.custom_wordlist.txt
- docs/changelog.rst
> chore: release 2.5.0

- craft_store/base_client.py
- craft_store/models/__init__.py
- craft_store/models/resource_revision_model.py
- tests/integration/test_list_resource_revisions.py
- tests/integration/test_update_resource_revisions.py
- tests/unit/models/test_resource_revision_model.py
- tests/unit/test_base_client.py
-----
~~Requires #129~~  ~~Requires #131~~
Fixes #126
> feat: update resource revisions

- tests/integration/charmhub/test_charmhub_workflow.py
- tests/integration/conftest.py
-----
An early version of a full charm workflow integration test. I'm writing it to help test #124, but these initial steps don't require any of that code and still test things our existing tests don't, so I thought it worth bringing on its own.
> tests: Scaffold the Charmhub workflow test

- .github/workflows/tests.yaml
> ci: de-duplicate artifact names

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
> chore: release 2.6.0

- pyproject.toml
- tests/unit/models/test_account_model.py
> style(types): update pyright

- .bumpversion.cfg
- craft_store/__init__.py
- docs/changelog.rst
> chore: release 2.6.1

- craft_store/auth.py
> fix: catch keyring locked error

- craft_store/auth.py
> fix: add workaround for libssl in core20

- .github/workflows/tests.yaml
- craft_store/auth.py
- craft_store/base_client.py
- craft_store/creds.py
- craft_store/endpoints.py
- craft_store/errors.py
- craft_store/http_client.py
- craft_store/models/_base_model.py
- craft_store/models/_charm_model.py
- craft_store/models/_common_list_releases_model.py
- craft_store/models/account_model.py
- craft_store/models/charm_list_releases_model.py
- craft_store/models/registered_name_model.py
- craft_store/models/release_request_model.py
- craft_store/models/resource_revision_model.py
- craft_store/models/revisions_model.py
- craft_store/models/snap_list_releases_model.py
- craft_store/models/track_model.py
- craft_store/store_client.py
- craft_store/ubuntu_one_store_client.py
- pyproject.toml
- tests/integration/conftest.py
- tests/unit/conftest.py
- tests/unit/test_auth.py
- tests/unit/test_ubuntu_one_store_client.py
- tox.ini
> bump minimal python version to 3.10

- craft_store/base_client.py
- craft_store/creds.py
- craft_store/endpoints.py
- craft_store/models/_base_model.py
- craft_store/models/_charm_model.py
- craft_store/models/_common_list_releases_model.py
- craft_store/models/charm_list_releases_model.py
- craft_store/models/registered_name_model.py
- craft_store/models/release_request_model.py
- craft_store/models/resource_revision_model.py
- craft_store/models/revisions_model.py
- craft_store/models/snap_list_releases_model.py
- craft_store/models/track_guardrail_model.py
- craft_store/models/track_model.py
- pyproject.toml
- tests/unit/conftest.py
- tests/unit/models/test_registered_name_model.py
- tests/unit/models/test_resource_revision_model.py
- tests/unit/models/test_track_guardrail_model.py
- tests/unit/models/test_track_model.py
- tests/unit/test_base_client.py
> build(deps)!: update to pydantic 2

- .bumpversion.cfg
- craft_store/__init__.py
- docs/.custom_wordlist.txt
- docs/changelog.rst
> docs: update version to 3.0.0

- .pre-commit-config.yaml
- pyproject.toml
- tests/integration/conftest.py
- tests/integration/test_auth.py
- tests/unit/conftest.py
- tests/unit/models/test_charm_list_releases_model.py
- tests/unit/models/test_snap_list_releases_model.py
- tests/unit/test_auth.py
- tests/unit/test_base_client.py
- tests/unit/test_creds.py
- tests/unit/test_http_client.py
- tests/unit/test_store_client.py
- tests/unit/test_ubuntu_one_store_client.py
> Update ruff to 0.6

- craft_store/auth.py
- pyproject.toml
> fix: make compatible with keyring 25

- docs/changelog.rst
-----
Unblocks https://github.com/canonical/snapcraft/issues/5048
> docs(changelog): add 3.0.1 release notes

- pyproject.toml
> fix: use correct README in pyproject.toml

- docs/changelog.rst
-----
For https://github.com/canonical/snapcraft/issues/5077
> docs(changelog): add 3.0.2 release notes

- docs/changelog.rst
-----
Changelog link: https://canonical-craft-store--246.com.readthedocs.build/en/246/changelog/#id1
> docs(changelog): release 3.1.0

- .github/renovate.json5
> fix: point to the correct renovate file

- .pre-commit-config.yaml
- tests/integration/charmhub/test_charmhub_workflow.py
- tests/integration/test_register_unregister.py
- tests/unit/test_auth.py
- tests/unit/test_creds.py
> style: autoformat with ruff 0.9

- craft_store/models/__init__.py
- craft_store/publisher/__init__.py
- craft_store/publisher/_publishergw.py
- craft_store/publisher/_request.py
- craft_store/publisher/_response.py
- tests/integration/publisher/test_read.py
- tests/integration/publisher/test_write.py
- tests/unit/publisher/test_publishergateway.py
These are the endpoints needed to handle promoting a revision from one channel to another.
-----
CRAFT-2708
> feat(publishergw): endpoints for promotion

- .github/.jira_sync_config.yaml
Update the Jira integration for our new labels
-----
CRAFT-4217
> ci: update Jira integration

- .github/workflows/tics.yaml
- common.mk
- pyproject.toml
- uv.lock
> ci: add tics workflow

- .github/workflows/tics.yaml
-----
A quick fix to correct the Tiobe project name and make testing easier.
> ci: fix tiobe project name, enable easier testing

- docs/custom_conf.py
- docs/howto/craft-cli-upload-progress.rst
> docs: fix linkcheck issues with documentation
