canonical/craft-store

docs/conf.py

Path needs to be set before importing craft_store which is where the
version is stored.
-------
-----

docs: set import path for requirements

---

craft_store/endpoints.py
tests/unit/test_endpoints.py

Charmhub and Snap Store use different paths for similar API calls.
This is an abstraction for that.
Additionally provides an internal method to convert the required
payload for the .tokens endpoint.
-------
-----

endpoints: new component to abstract endpoints for different stores (CRAFT-454)

---

craft_store/endpoints.py
craft_store/store_client.py
tests/unit/test_endpoints.py
tests/unit/test_store_client.py

Required in order to support attenuated macaroons that work with a set
of specific packages or channels.
A higher level Package class is introduced to simplify the
presentation of StoreClient's login method.
A RuntimeError is raised to ease development when improper package
types are used for each endpoint (Snap Store and Charmhub).
-------
-----

endpoints: support packages and channels (CRAFT-637)

---

craft_store/auth.py
craft_store/store_client.py
tests/integration/test_auth.py
tests/unit/test_auth.py
tests/unit/test_store_client.py

In order to allow a MemoryKeyring to be used together with environment
variables in an ephemeral workflow such as CI/CD.
-------
-----

auth: support credentials from the environment (CRAFT-638)

---

.readthedocs.yml

It is incompatible with the new build declaration.
-------
-----

readthedocs: remove legacy python.version

---

.readthedocs.yml

"requirements" needs to be its own list item.
-------
-----

readthedocs: type in configuration for requirements

---

.pylintrc
Makefile
craft_store/__init__.py
craft_store/base_client.py
craft_store/store_client.py
setup.cfg
tests/unit/test_store_client.py

The BaseClient is reusable between the Candid flow and the Ubuntu One
flow. Required implementation is done with an AbstractBaseClass and
abstractmethods to ensure the implementor does the right thing.
The BaseClient now also composes the HTTPClient instead of inheriting
from it to make it easier for subclassess to make unauthenticated http
calls without needing to change the signature for .request.
The overrides package was addedd to help pydocstyle not request
docstrings for overriden classes which also triggered pylint's
duplicate-code check (which is in any case disabled as the bigger
signatures in the methods also trigger it).
-------
-----

store client: split common StoreClient functionality to a base class (CRAFT-690)

---

craft_store/endpoints.py
tests/unit/test_endpoints.py
tests/unit/test_store_client.py

Charmhub has introduced a new endpoint for whoami which can provide
token information for the current authorizations used.
-------
-----

endpoints: update whoami endpoint for CHARMHUB (CRAFT-702)

---

README.md
craft_store/errors.py
craft_store/http_client.py
pyrightconfig.json
setup.cfg
tests/unit/test_errors.py
tests/unit/test_http_client.py

- added py.typed to match py.typed in setup.cfg
- corrected README.md for proper packaging
- float is not accepted as a total Retry value
- ignore typing for urllib3.exceptions
- exclude .tox from linters
-----

static: update excluded and changes from new errors

---

craft_store/auth.py
craft_store/errors.py
tests/unit/test_auth.py
tests/unit/test_errors.py
tests/unit/test_store_client.py

-----
With this change, the StoreClient raises on __init__ if no keyring is found.

auth: avoid MemoryKeyring in keyring and raise appropriately (CRAFT-771)

---

craft_store/auth.py
craft_store/errors.py
tests/unit/test_auth.py
tests/unit/test_errors.py

-----
`craft-store` to raise a more useful error when a credential is not parseable. 
Previous Behavior:
```
> > CHARMCRAFT_AUTH='12345' charmcraft login
charmcraft internal error: Error('Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4')
```
New Behavior:
```
> CHARMCRAFT_AUTH='12345' charmcraft login
charmcraft internal error: CredentialsNotParseable('Credentials could not be parsed.')
```
https://github.com/canonical/craft-store/issues/20

auth: raise error when credentials cannot be parsed (CRAFT-812)

---

craft_store/base_client.py
tests/unit/test_store_client.py
tests/unit/test_ubuntu_one_store_client.py

This was somehow missed, as seen from the unsused attribute which is now removed
and processed when passing the "host" parameter to Auth.
-----
This does have the drawback of forgetting of forgetting about existing logins.

store client: use netloc to reference keyring location (CRAFT-799)

---

craft_store/auth.py
craft_store/ubuntu_one_store_client.py
tests/unit/test_auth.py
tests/unit/test_ubuntu_one_store_client.py

Whislt the original implementation which was used in Snapcraft had the
Snap Store return a header with refresh information, the new backend
returns an error code.
This allows for macaroons to be refreshed properly by adding a force
option to set_credentials.
-----

ubuntu client: proper refresh macaroon

---

craft_store/auth.py
craft_store/errors.py
tests/unit/test_auth.py
tests/unit/test_errors.py

Obtaining the password from the keyring can fail if the keyring is not properly unlocked. In this case, handle the keyring exception and raise an appropriate Craft-store error.
-----
CRAFT-1622

auth: handle keyring unlocking errors

---

.github/workflows/tests.yaml
setup.cfg
tests/integration/conftest.py
tests/integration/test_auth.py
tests/integration/test_get_list_releases.py
tests/integration/test_register_unregister.py
tests/integration/test_release.py
tests/integration/test_upload.py

-----
We should probably get a service account for charmhub, but in the meantime this improves the testing a bit.
Outstanding issue: Charmhub credentials aren't used when running with a PR from an external repository, so it skips tests that require charmhub credentials. However, those tests will run on merge to main.

test: improve integration testing

---

.github/workflows/automatic-doc-checks.yml
.github/workflows/docs.yaml
.gitignore
.gitmodules
.readthedocs.yml
docs/.custom_wordlist.txt
docs/.sphinx/requirements.txt
docs/.wordlist.txt
docs/Makefile
docs/conf.py
docs/custom_conf.py
pyproject.toml
tox.ini

Fixes: https://github.com/canonical/craft-store/issues/100
CRAFT-2077

feat(docs): use canonical starter pack

---

craft_store/auth.py
pyproject.toml
tests/unit/conftest.py
tests/unit/test_auth.py

Useful when a keyring is not available, such as when running on a headless system.
-----
Fixes #109 #58

feat: add file based backend as a fallback

---

craft_store/base_client.py
craft_store/models/resource_revision_model.py
tests/integration/test_list_resource_revisions.py
tests/unit/test_base_client.py

-----
Requires #128
fixes #125

feat: list resource revisions for a package

---

.github/renovate.json5

We'd be ignoring these updates anyway, so let's just prevent Renovate from doing them.
-----

chore(deps): don't let renovate update pydantic or protobuf

---

pyproject.toml

https://github.com/canonical/craft-store/issues/162
-----

fix: workaround for keyring 25 incompatibility

---

.bumpversion.cfg
craft_store/__init__.py
docs/.custom_wordlist.txt
docs/changelog.rst

- Disable legacy libssl providers. This is a workaround to prevent a crash
when loading cryptography in focal.

Release 2.6.2

---

.github/workflows/tests.yaml
pyproject.toml
tests/unit/test_store_client.py
tox.ini

build(deps): use ruff from snap

---

craft_store/creds.py
tests/unit/test_creds.py

-----
Pydantic 2's `model_copy()` function cannot update fields by their alias.  
Fixes https://github.com/canonical/snapcraft/issues/5048

fix: update discharge macaroons

---

craft_store/auth.py
docs/.custom_wordlist.txt
docs/changelog.rst

-----
Merges the fix from https://github.com/canonical/craft-store/pull/175 into main.
This explains https://github.com/canonical/snapcraft/issues/5077 because snapcraft 8.3 was using craft-store 2.6.2 and the fix was lost when snapcraft 8.4 upgraded to craft-store 3.0.
We will need a craft-store release after this lands.

chore(merge): 2.6.2 into main

---

.github/workflows/release-publish.yaml

-----
I'm not sure why this is not needed in other repos, but CI is failing: https://github.com/canonical/craft-store/actions/runs/11130571185/job/30933712504

ci: update permissions for publishing to pypi

---

craft_store/auth.py
craft_store/base_client.py
craft_store/store_client.py
craft_store/ubuntu_one_store_client.py
docs/changelog.rst
tests/unit/test_auth.py
tests/unit/test_store_client.py
tests/unit/test_ubuntu_one_store_client.py

Previously, we were falling back to `FileKeyring` if and only if `SecretService` provider was erroring out, not if it was not available at all.
This PR allows applications to opt-in for fallback to use a file to store secrets in a system without `SecretService` provider.
(CRAFT-3620)

feat: add opt-in fallback to FileKeyring

---

craft_store/models/release_request_model.py
pyproject.toml
tests/unit/models/test_registered_name_model.py

Silent error, that was introduced with pydantic 2.10 release until it's fixed.
For reference: https://github.com/pydantic/pydantic/issues/10950
https://github.com/canonical/craft-application/pull/566
There was also a change in `pydantic_core`, which made `Url` incomparable with `AnyHttpUrl`. Somehow in my local environment it only failed when tests were run through `tox`, not directly. From test logs:
```
FAILURE: check https://canonical.com/ == https://canonical.com/
test_registered_name_model.py:99 in test_unmarshal() -> check.equal(actual.website, pydantic.networks.HttpUrl(json_dict.get("website")))
```

chore(lint): get around pydantic 2.10.x bugs

---

craft_store/store_client.py
craft_store/ubuntu_one_store_client.py
uv.lock

Fixes currently failing pipeline in `craft-store`.
* Update Jinja2 dependency to address CVE scanning result.
* Disable `S105` false-positive for the `TOKEN_TYPE`

build(deps): update Jinja2

---

craft_store/publisher/_response.py
docs/reference/changelog.rst
tests/unit/publisher/test_publishergateway.py

I used the wrong resource model causing failures during release if the store doesn't return a type.
-----
CRAFT-4032

fix(publishergateway): used the wrong resource model

---

pyproject.toml

This fixes minimum-deps tests, as seen broken in #275 
-----

build(deps): constrain the minimum version of sphinx-rtd-theme

---

pyproject.toml
uv.lock

Prevents https://osv.dev/vulnerability/GHSA-79v4-65xg-pq4g
-----

build(deps): constrain cryptography to >= 44.0.1

---

craft_store/publisher/_publishergw.py
tests/unit/publisher/test_publishergateway.py

A recent-ish change in craft-cli made an error's 'details' get shown to the user by default. This means that CraftStoreErrors with a single store error would get the actual error message printed twice - once from the 'brief' and once from the 'details'. Instead, log the error list (as it has relevant error codes).
-----

feat: don't use error list as details

---

.github/workflows/qa.yaml

-----
Required test changes are at https://github.com/canonical/canonical-repo-automation/pull/286

ci: switch to public runners
